# Generated by Django 4.1.7 on 2023-03-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name_plural': 'hobbies'},
        ),
    ]
