# Generated by Django 4.1.7 on 2023-03-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_education_accolades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='current_employer',
            field=models.CharField(help_text='yes or no', max_length=50),
        ),
    ]
