# Generated by Django 4.1.7 on 2023-03-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='end_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
