# Generated by Django 4.1.7 on 2023-03-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_alter_hobby_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('picture', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
